project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!archived/"

website:
  title: "R Training - TIDAL Lectures"
  site-url: https://emorytidal.netlify.app/
  description: "Melinda Higgins R Training for TIDAL Lecture Series"
  
  sidebar:
    search: true
    logo: tidal_logo.png
    pinned: true
    align: center
    background: "#6600B4"
    tools: 
      - icon: house-fill
        href: https://www.project-tidal.org/
      - icon: github
        href: https://github.com/melindahiggins2000/emory_tidal_Rlectures
    
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: module131_IntroRRStudio.qmd
        text: "1.3.1: Introduction to the R and R Studio"
      - href: module132_DataWrangling.qmd
        text: "1.3.2: Data Wrangling"
      - href: module133_DataVis.qmd
        text: "1.3.3: Data Visualization"
      - href: module134_MissingWeight.qmd
        text: "1.3.4: Missing Data and Sampling Weights"
      - href: module135_StatisticalTests.qmd
        text: "1.3.5: Statistical Tests and Models"
      - href: module136_ReproducibleResearch.qmd
        text: "1.3.6: Reproducible Research Principles"
      - href: PRAMS.qmd
        text: "Setup Project for PRAMS Data Analysis"
      - href: additionalResources.qmd
        text: "Additional Help and Resources"

  page-footer:
    background: light
    left: "[![](https://img.shields.io/badge/License-CC_BY--NC--ND_4.0-lightgrey.svg)](https://creativecommons.org/licenses/by-nc-nd/4.0/)"
    center: "Copyright 2025, [Melinda Higgins, PhD.](https://melindahiggins.netlify.app/) [{{< fa brands linkedin >}}](https://www.linkedin.com/in/melindahiggins2000/)  [{{< fa brands google-scholar >}}](https://scholar.google.com/citations?user=-4aU-VkAAAAJ&hl=en)  [{{< fa brands github >}}](https://github.com/melindahiggins2000)  [{{< fa envelope >}}](mailto:mkhiggi@emory.edu)"

format:
  html:
    theme: 
      - yeti
      - mkh_styles.scss
    mainfont: Nunito
    toc: true
    toc-depth: 4
    page-layout: full
    code-link: true
    knitr:
      opts_chunk:
        message: false
        warning: false
  pdf:
    include-in-header: 
      text: |
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \renewcommand{\footrulewidth}{0.4pt}
        \setlength{\headsep}{50pt}
        \fancyhead[L]{\includegraphics[width=1cm]{tidal_logo.png} \href{https://www.project-tidal.org/}{Project TIDAL}}
        \fancyhead[R]{Module 1.3: Data Analytics Using R}
        \fancyfoot[L]{\href{https://creativecommons.org/licenses/by-nc-nd/4.0/}{\includegraphics[width=2cm]{cc_by_nc_nd.png}}}
        \fancyfoot[C]{\url{emorytidal.netlify.app}}
        \fancyfoot[R]{\thepage}
            
