---
title: "Research Interest, Skills, Experience and Education"
---

::: panel-tabset
## **Contact Me**

* [melinda.higgins@emory.edu](mailto:melinda.higgins@emory.edu)
* 404-727-5180
* Emory University - School of Nursing
* 1520 Clifon Road; Atlanta, GA 30322

```{r out.width='80%', echo=FALSE}
library(leaflet)
leaflet() %>% addTiles() %>%
  setView(-84.32377530428083, 33.79818304004407, zoom = 17) %>%
  addPopups(
    -84.32377530428083, 33.79818304004407, 
    'Here is the <b>School of Nursing</b>'
  )
```

## **Research Interests**

* Reproducible Research
* Dynamic Documentation
* R programming
* Pattern Recognition
* Multivariate Statistical Modeling

## **Skills**

* Biostatistics and Research
* [R](https://cran.r-project.org/) and formally [S/S+](https://en.wikipedia.org/wiki/S_(programming_language))
* [Rmarkdown](https://rmarkdown.rstudio.com/) and [Quarto](https://quarto.org/)
* [GIT](https://git-scm.com/) and [Github](https://github.com/melindahiggins2000)
* [SPSS](https://www.ibm.com/spss)
* [SAS](https://www.sas.com/en_us/home.html)
* [MATLAB](https://www.mathworks.com/products/matlab.html)
* [Pascal](https://en.wikipedia.org/wiki/Pascal_(programming_language))
* [FORTRAN](https://fortran-lang.org/)
* Others: [awk](https://en.wikipedia.org/wiki/AWK), [sed](https://en.wikipedia.org/wiki/Sed), [perl](https://www.perl.org/)

## **Job Titles and Experience**

* Emory University, Atlanta, GA; School of Nursing; Office of Nursing Research
    - [Director Biostatistics and Data Core](https://www.nursing.emory.edu/pages/onrstatsdata) [2021-current]
    - [Research Professor](https://www.nursing.emory.edu/faculty-staff/melinda-k-higgins) [2019 - current]
    - Associate Research Professor [2007 - 2019]
    
* [Georgia Tech Research Institute, Atlanta, GA](https://gtri.gatech.edu/)
    - Director of the National guard bureau (NGB) Technology Consortium Program [1998 - 2011]
    - Principal Research Scientist [2005 - 2011]
    - Senior Research Scientist [2000 - 2005]
    - Research Scientist II [1996 - 2000]
    - Temporary Technical Advisor [1995 - 1996]

## **Education**

* PhD in Chemometrics/Analytical Chemistry
    - Dissertation Title: _Chemometric analysis of gas chromatographic/mass spectrometric and spectroscopic data for classification and modeling of chemical structure and composition_
    - University of South Carolina
    - 1994
* MS in Statistics [Experimental Design]
    - Thesis Title: _The integrated michaelis-menten model: Estimation, inference, experimental designs, and derivation from the classical michaelis-menten model_
    - University of South Carolina
    - 1995
* BS Chemistry & Mathematics [Dual Major]
    - Saint Andrews Presbyterian College
    - 1989

:::


