---
title: "Theme 1. Measurement and Prediction of IPV"
---

\thispagestyle{fancy}

## Module 1.3: Data Analytics Using R

Presented by [Melinda Higgins, PhD](https://melindahiggins.netlify.app/)

Module 1.3 will introduce the learner to writing code in the R language and utilizing the RStudio IDE (integrated development environment). This module will include 6 sessions - the first 3 will be asynchronous-online (AO) and the last 3 will be in-person (IP).

The 6 sessions are:

* [1.3.1: Introduction to R and R Studio (AO)](./module131_IntroRRStudio.html)
* [1.3.2: Data Wrangling (AO)](./module132_DataWrangling.html)
* [1.3.3: Data Visualization (AO)](./module133_DataVis.html)
* [1.3.4: Missing data and sampling weight (IP)](./module134_MissingWeight.html)
* [1.3.5: Statistical tests and models (IP)](./module135_StatisticalTests.html)
* [1.3.6: Putting reproducible research principles into practice (IP)](./module136_ReproducibleResearch.html)

---

## Project TIDAL

[Project TIDAL](https://www.project-tidal.org/) is an NIH-funded R25 study (1 R25 NR021324-01 ), co-led by Drs. [Sangmi Kim](https://www.nursing.emory.edu/faculty-staff/sangmi-kim) and [Ran Xiao](https://www.nursing.emory.edu/faculty-staff/ran-xiao) from Nell Hodgson Woodruff School of Nursing at Emory University. 

The objective of the study is to develop a short course titled “Trauma-Informed Data Science and Digital Health Technologies to Prevent Intimate Partner Violence (IPV) among Pregnant/Postpartum Women” targeting early-career researchers (predoctoral, postdoctoral, and junior faculty) from diverse backgrounds across the U.S. 

---





