---
title: "1.3.5: Statistical Tests and Models"
subtitle: "(In Person)"
bibliography: ./packages.bib
nocite: |
  @*
format:
  html: default
  pdf: default
editor_options: 
  chunk_output_type: console
---

\thispagestyle{fancy}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE,
                      message = FALSE,
                      warning = FALSE)
knitr::opts_chunk$set(
  comment = '', fig.width = 6, fig.height = 6
)
# be sure to cover these
# https://easystats.github.io/easystats/
# and tidymodels, broom, purrr, etc
# effect sizes
```

## COMING SUMMER 2025

Module "1.3.5: Statistical Tests and Models" will be posted prior to the In-Person Workshops in Summer 2025.

## Session Objectives

1. Develop linear and logistic regression models.
2. (Use a survey sampling weight to generate more representative descriptive and inferential statistical values.) - Currently, this objective is under the Module 1.3.4: Missing data and sampling weight.
3. Interpret a model output.

Key points to cover:

1. Run multivariate linear regression models with R.
2. Run multivariate logistic regression models with R.
3. Include interaction terms in regression models.
4. (R packages for complex survey data (e.g., survey package)
    - R codes to generate weighted descriptive statistics and contingency tables, as well as to develop weighted linear models)
5. Interpret a model output.
6. (Compare the outputs of unweighted and weighted models.)

